// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where HEAD points.
 */
export type Head = { "kind": "branch", name: string, } | { "kind": "detached", oid: string, } | { "kind": "unborn", name: string, };

/**
 * The multi-step operation the repository is in the middle of, detected from the files git
 * leaves in the git dir rather than from porcelain.
 */
export type OpState = "clean" | "merge" | "rebase" | "cherry_pick" | "revert" | "bisect";

/**
 * What `coral open` reports.
 */
export type RepoInfo = { path: string, gitDir: string, commonDir: string, isBare: boolean, gitVersion: string, head: Head, state: OpState, 
/**
 * Whether a commit-graph is present. Its absence is the single biggest predictor of a
 * slow first paint on a large repository.
 */
commitGraph: boolean, };
