// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Blame = { chunks: Array<BlameChunk>, 
/**
 * Keyed by oid. Git sends a commit's details once and then refers back to it, so this is
 * far smaller than one entry per chunk on a file with a long history.
 */
commits: { [key in string]: BlameCommit }, };

/**
 * A run of consecutive lines attributed to one commit.
 */
export type BlameChunk = { oid: string, 
/**
 * First line in the file as it is now, 1-based.
 */
finalLine: number, 
/**
 * First line in the file as it was at `oid`, 1-based.
 */
origLine: number, lines: number, };

/**
 * What a commit contributes to a blame, shared by every chunk that names it.
 */
export type BlameCommit = { oid: string, author: Signature, summary: string, 
/**
 * The path the content had at this commit, which differs after a rename.
 */
filename: string, };

/**
 * One region of a conflicted file.
 */
export type Block = { "kind": "common", lines: string[], } | { "kind": "conflict", base: string[], ours: string[], theirs: string[], };

/**
 * A conflicted file broken into blocks.
 */
export type Blocks = { blocks: Array<Block>, };

/**
 * How one side of the index/worktree pair changed.
 */
export type Change = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "type_changed" | "untracked" | "ignored";

/**
 * A file a commit changed.
 */
export type ChangedFile = { path: string, oldPath: string | null, change: FileChange, };

/**
 * One commit's metadata, without its tree or diff.
 */
export type Commit = { oid: string, parents: Array<string>, author: Signature, committer: Signature, 
/**
 * First line of the message.
 */
summary: string, 
/**
 * Everything after the first blank line; empty when there is none.
 */
body: string, };

/**
 * Everything the details panel shows for one commit.
 */
export type CommitDetail = { commit: Commit, files: Array<ChangedFile>, };

/**
 * What the graph shows next to a row: who wrote it and its first line.
 *
 * Deliberately smaller than [`Commit`]. The graph needs this for a screenful of rows at a
 * time; carrying full parent lists and bodies would undo the row store's compactness.
 */
export type CommitMeta = { oid: string, author: string, email: string, time: number, summary: string, 
/**
 * The start of the message body, for the dimmed continuation the graph shows after the
 * summary. Truncated because a screenful of full bodies is far more than the row needs.
 */
body: string, };

/**
 * Which side of a conflict did what. Taken from the XY of a `u` entry, whose codes mean
 * something different from an ordinary entry's.
 */
export type ConflictKind = "both_modified" | "both_added" | "both_deleted" | "added_by_us" | "added_by_them" | "deleted_by_us" | "deleted_by_them";

/**
 * One file needing a decision.
 */
export type ConflictedFile = { path: string, kind: ConflictKind, 
/**
 * Binary files offer only whole-file choices; there are no blocks to pick between.
 */
binary: boolean, 
/**
 * One side deleted the file, so keeping or deleting is the only meaningful choice.
 */
deleteModify: boolean, };

/**
 * What happened to a file between two trees.
 */
export type FileChange = "added" | "deleted" | "modified" | "renamed" | "copied" | "unmerged";

export type FileDiff = { path: string, oldPath: string | null, change: FileChange, binary: boolean, 
/**
 * Lines added and removed. `None` for a binary file, where git reports no counts.
 */
added: number | null, removed: number | null, 
/**
 * Empty for a binary file, a pure rename, or a mode-only change.
 */
hunks: Array<Hunk>, 
/**
 * Set when the file was not read because it exceeds the size guard.
 */
tooLarge: boolean, };

export type GitRef = { 
/**
 * Full name, e.g. `refs/heads/main`.
 */
name: string, 
/**
 * The name the UI shows, e.g. `main` or `origin/main`.
 */
short: string, kind: RefKind, 
/**
 * What the ref points at. For an annotated tag this is the tag object.
 */
target: string, 
/**
 * The commit an annotated tag ultimately points at. `None` for everything else.
 */
peeled: string | null, upstream: string | null, ahead: number, behind: number, };

/**
 * Where HEAD points.
 */
export type Head = { "kind": "branch", name: string, } | { "kind": "detached", oid: string, } | { "kind": "unborn", name: string, };

export type Hunk = { 
/**
 * The `@@ ... @@` line verbatim, including any trailing section heading.
 */
header: string, oldStart: number, oldLines: number, newStart: number, newLines: number, lines: Array<Line>, };

/**
 * A name and an address, either of which may be unset.
 *
 * `None` is not the empty string. git refuses to commit with an empty `user.email` and falls
 * back to the level above with an absent one, so the two mean opposite things.
 */
export type Identity = { name: string | null, email: string | null, };

/**
 * The identity as it stands for one repository: what git will use, what it inherits, what
 * the repository sets of its own.
 */
export type IdentityScopes = { effective: Identity, global: Identity, local: Identity, };

export type Line = { kind: LineKind, text: string, oldNo: number | null, newNo: number | null, 
/**
 * The file does not end with a newline, and this is its last line.
 */
noNewline: boolean, };

export type LineKind = "context" | "add" | "remove";

/**
 * The result of an operation that may stop for conflicts.
 */
export type OpOutcome = { 
/**
 * True when the operation finished; false when it stopped and needs resolution.
 */
completed: boolean, state: OpState, 
/**
 * Paths left unmerged, when it stopped.
 */
conflicts: Array<string>, 
/**
 * git's own explanation, when it stopped.
 */
message: string, };

/**
 * The multi-step operation the repository is in the middle of, detected from the files git
 * leaves in the git dir rather than from porcelain.
 */
export type OpState = "clean" | "merge" | "rebase" | "cherry_pick" | "revert" | "bisect";

/**
 * Everything known about the operation in progress.
 */
export type Operation = { state: OpState, labels: SideLabels, 
/**
 * Present for a rebase, which replays many commits.
 */
progress: Progress | null, 
/**
 * The branch being rebased, as a short name.
 */
headName: string | null, 
/**
 * The commit the operation stopped on.
 */
stoppedAt: string | null, 
/**
 * True for `rebase -i`.
 */
interactive: boolean, 
/**
 * Whether git has an operation it can be told to continue, abort or skip.
 *
 * False for a conflicted index with no marker file: `merge --no-commit`, `cherry-pick
 * --no-commit`, and a stash that would not apply all leave one. The state is reported as
 * a merge because that is what git's own status calls it, but there is nothing to
 * continue — the files are resolved, staged and committed like any other change, and
 * `git merge --continue` answers that no merge is in progress.
 */
resumable: boolean, 
/**
 * True when this is `git am` rather than a rebase.
 *
 * The two leave the same files behind and are settled the same way, so the state is
 * `Rebase` for both. What differs is what to call it and which sides it has: applying a
 * patch does not reverse them, and telling somebody who just opened a patch file that a
 * rebase is in progress with its sides reversed is two pieces of wrong information.
 */
applying: boolean, };

/**
 * How far through a multi-step operation git has got.
 */
export type Progress = { current: number, total: number, };

/**
 * What happened to one ref during a push.
 */
export type PushFlag = "ok" | "forced" | "deleted" | "new" | "rejected" | "up_to_date";

export type PushResult = { flag: PushFlag, local: string, remote: string, 
/**
 * git's own words, e.g. "[new branch]" or the reason for a rejection.
 */
summary: string, };

/**
 * What kind of thing a ref names.
 */
export type RefKind = { "kind": "local_branch" } | { "kind": "remote_branch", remote: string, } | { "kind": "tag", annotated: boolean, } | { "kind": "stash" } | { "kind": "other" };

/**
 * A configured remote.
 */
export type Remote = { name: string, fetchUrl: string, 
/**
 * Differs from `fetch_url` when the user configured a separate push URL.
 */
pushUrl: string, };

/**
 * What changed since the last notification. Never "nothing": an empty set is not emitted.
 */
export type RepoChanged = { 
/**
 * `refs/**`, `packed-refs`, `HEAD`, or the reflogs.
 */
refs: boolean, 
/**
 * The index file.
 */
index: boolean, 
/**
 * Anything in the worktree that is not inside the git dir.
 */
worktree: boolean, 
/**
 * A multi-step operation started, advanced, or ended.
 */
ops: boolean, 
/**
 * The commit-graph file changed, which normally means the background
 * `git commit-graph write` finished and the walk is now worth redoing.
 */
graph: boolean, };

/**
 * What `coral open` reports.
 */
export type RepoInfo = { path: string, gitDir: string, commonDir: string, isBare: boolean, gitVersion: string, head: Head, state: OpState, 
/**
 * Whether a commit-graph is present. Its absence is the single biggest predictor of a
 * slow first paint on a large repository.
 */
commitGraph: boolean, };

/**
 * What the two sides of a conflict should be called in the interface.
 *
 * Never "ours" and "theirs". During a rebase those words are actively misleading: git replays
 * your commits on top of the target, so stage 2 ("ours") is the branch you are rebasing
 * *onto* and stage 3 ("theirs") is your own work. Presenting the raw words is how every git
 * client confuses its users.
 */
export type SideLabels = { 
/**
 * What stage 2 is.
 */
ours: string, 
/**
 * What stage 3 is.
 */
theirs: string, 
/**
 * True during a rebase, where the sides read backwards from what a user expects. The UI
 * states this once rather than leaving people to work it out.
 */
swapped: boolean, };

/**
 * A person and when they acted. Author and committer are shown separately in the UI, because
 * a rebased or cherry-picked commit has two different answers.
 */
export type Signature = { name: string, email: string, 
/**
 * Seconds since the epoch.
 *
 * Declared as a number rather than ts-rs's default `bigint` for `i64`: serde writes it as
 * a JSON number, so `bigint` would describe something the wire never carries. Seconds are
 * exact in a double until well past the year 200,000.
 */
time: number, };

/**
 * Everything the signing settings screen shows.
 */
export type SigningConfig = { format: SigningFormat, 
/**
 * Empty when git's default for the format is in use.
 */
program: string, 
/**
 * `user.signingkey`. Empty when git is left to choose.
 */
key: string, signCommits: boolean, signTags: boolean, };

/**
 * The signature format git will produce.
 */
export type SigningFormat = "openpgp" | "x509" | "ssh";

/**
 * A key that could sign.
 */
export type SigningKey = { 
/**
 * What goes in `user.signingkey`: a full fingerprint, or a path for ssh.
 */
id: string, 
/**
 * Who the key belongs to, for the list.
 */
label: string, 
/**
 * Seconds since the epoch, or `None` for a key that does not expire.
 */
expires: bigint | null, 
/**
 * True when it has expired already, which is why it is still listed rather than dropped.
 */
expired: boolean, };

/**
 * What this repository sets for itself.
 *
 * `None` means the repository says nothing and the app-level setting applies. That is a
 * different state from a value that happens to match, and the difference is what lets a
 * setting be cleared back to inheriting rather than pinned to whatever it inherited.
 */
export type SigningOverrides = { format: SigningFormat | null, program: string | null, key: string | null, signCommits: boolean | null, signTags: boolean | null, };

/**
 * Signing as it stands for one repository: what will happen, what it inherits, what it sets.
 */
export type SigningScopes = { 
/**
 * What git will actually do here.
 */
effective: SigningConfig, 
/**
 * The app-level defaults, which every repository inherits until it says otherwise.
 */
global: SigningConfig, 
/**
 * What this repository sets for itself.
 */
local: SigningOverrides, };

/**
 * How git is told to reach an ssh server.
 */
export type SshConfig = { 
/**
 * True when nothing overrides `ssh`, so the running agent decides which key to offer.
 */
useAgent: boolean, 
/**
 * The private key git is pointed at, when it is pointed at one.
 */
privateKey: string, 
/**
 * Its public half. git never needs this; it is what gets uploaded to the host.
 */
publicKey: string, 
/**
 * `core.sshCommand`, verbatim, since a user may have written one by hand.
 */
command: string, 
/**
 * `credential.helper`, so the screen can say which one is answering.
 */
credentialHelper: string, };

/**
 * One key pair found on disk.
 */
export type SshKey = { 
/**
 * The private key's path, which is what `core.sshCommand` names.
 */
path: string, 
/**
 * The public half, when it is beside the private one.
 */
publicPath: string, 
/**
 * The comment at the end of the public key, usually `user@host`.
 */
comment: string, 
/**
 * `ssh-ed25519`, `ssh-rsa`, and so on.
 */
kind: string, };

/**
 * What this repository sets for itself. `None` means it inherits.
 */
export type SshOverrides = { 
/**
 * The private key to use here. Setting it writes `core.sshCommand`.
 */
privateKey: string | null, publicKey: string | null, credentialHelper: string | null, };

/**
 * Ssh as it stands for one repository: what will happen, what it inherits, what it sets.
 */
export type SshScopes = { effective: SshConfig, global: SshConfig, local: SshOverrides, };

/**
 * One entry on the stash stack.
 */
export type StashEntry = { 
/**
 * Position on the stack, which is what `stash@{n}` means and what apply and drop take.
 */
index: number, oid: string, 
/**
 * The branch it was made on, when git recorded one.
 */
branch: string | null, 
/**
 * What git wrote, with the "WIP on <branch>: " it puts in front removed.
 */
message: string, 
/**
 * Seconds since the epoch.
 */
time: bigint, };

export type Status = { branch: string | null, oid: string | null, upstream: string | null, ahead: bigint, behind: bigint, stashCount: number, entries: Array<StatusEntry>, };

export type StatusEntry = { path: string, 
/**
 * Where a rename or copy came from.
 */
origPath: string | null, index: Change, worktree: Change, conflict: ConflictKind | null, 
/**
 * Rename or copy similarity, 0-100.
 */
score: number | null, 
/**
 * True when the entry is a submodule, whose state git reports separately.
 */
submodule: boolean, 
/**
 * The file's mode changed even if its content did not.
 */
modeChanged: boolean, };

/**
 * What to do with one commit during an interactive rebase.
 */
export type Step = "pick" | "reword" | "edit" | "squash" | "fixup" | "drop";

/**
 * A submodule declared in `.gitmodules`.
 */
export type Submodule = { 
/**
 * The `.gitmodules` subsection name, which need not match the path.
 */
name: string, 
/**
 * Slash-separated and relative to the worktree root, as git records it.
 */
path: string, url: string, 
/**
 * The commit the superproject pins, absent when the path is not a gitlink in the index.
 */
pinned: string | null, 
/**
 * True once the submodule has been cloned; only then can it be opened.
 */
initialised: boolean, };

/**
 * A submodule's recorded commit, read from inside the submodule itself.
 */
export type SubmoduleRevision = { oid: string, summary: string, 
/**
 * Seconds since the epoch, as git reports author time.
 */
time: bigint, 
/**
 * True when the working copy sits exactly where the superproject pins it.
 */
inSync: boolean, };

/**
 * A rebase todo list, in the order the commits will be replayed.
 *
 * Note that this is the reverse of how the graph shows them: git replays oldest first, while
 * the UI lists newest first. The conversion happens once, here, rather than in every caller.
 */
export type Todo = { items: Array<TodoItem>, };

/**
 * One line of a rebase todo list.
 */
export type TodoItem = { step: Step, oid: string, summary: string, 
/**
 * The replacement message for a [`Step::Reword`]. Never written to the todo file.
 */
message: string | null, };

/**
 * One working tree attached to the repository, the main one included.
 */
export type Worktree = { path: string, 
/**
 * Empty for a worktree that has never been checked out.
 */
head: string, 
/**
 * The branch checked out there, short form. None when the head is detached.
 */
branch: string | null, 
/**
 * True while another process holds it, which is what stops a concurrent checkout.
 */
locked: boolean, 
/**
 * True when the main worktree of a bare repository, which has no files of its own.
 */
bare: boolean, };
