// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How one side of the index/worktree pair changed.
 */
export type Change = "unmodified" | "modified" | "added" | "deleted" | "renamed" | "copied" | "type_changed" | "untracked" | "ignored";

/**
 * Which side of a conflict did what. Taken from the XY of a `u` entry, whose codes mean
 * something different from an ordinary entry's.
 */
export type ConflictKind = "both_modified" | "both_added" | "both_deleted" | "added_by_us" | "added_by_them" | "deleted_by_us" | "deleted_by_them";

/**
 * Where HEAD points.
 */
export type Head = { "kind": "branch", name: string, } | { "kind": "detached", oid: string, } | { "kind": "unborn", name: string, };

/**
 * The multi-step operation the repository is in the middle of, detected from the files git
 * leaves in the git dir rather than from porcelain.
 */
export type OpState = "clean" | "merge" | "rebase" | "cherry_pick" | "revert" | "bisect";

/**
 * What `coral open` reports.
 */
export type RepoInfo = { path: string, gitDir: string, commonDir: string, isBare: boolean, gitVersion: string, head: Head, state: OpState, 
/**
 * Whether a commit-graph is present. Its absence is the single biggest predictor of a
 * slow first paint on a large repository.
 */
commitGraph: boolean, };

export type Status = { branch: string | null, oid: string | null, upstream: string | null, ahead: bigint, behind: bigint, stashCount: number, entries: Array<StatusEntry>, };

export type StatusEntry = { path: string, 
/**
 * Where a rename or copy came from.
 */
origPath: string | null, index: Change, worktree: Change, conflict: ConflictKind | null, 
/**
 * Rename or copy similarity, 0-100.
 */
score: number | null, 
/**
 * True when the entry is a submodule, whose state git reports separately.
 */
submodule: boolean, 
/**
 * The file's mode changed even if its content did not.
 */
modeChanged: boolean, };
